name: automerge
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
  # status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.14.1
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
          MERGE_REMOVE_LABELS: "automerge"
          # Using an unused label here to disable updating because using autoupdate action instead
          UPDATE_LABELS: "disabled"
